/**
 * Catálogo seed de `enemy_types`: 8 comuns (unlock a cada 90s) + bosses.
 */

export type EnemyTypeSeedRow = {
  name: string;
  isBoss: boolean;
  hpBase: number;
  speed: number;
  damage: number;
  attackSpeed: number;
  color: string;
  scale: number;
  unlockTime: number;
  xpReward: number;
  goldReward: number;
  normalDiamondChance: number;
  purpleDiamondChance: number;
};

/** Nomes legados removidos ao reseedar (substituídos pelos 8 progressivos). */
export const OBSOLETE_ENEMY_TYPE_NAMES = ["Normal", "Dasher", "Ranged"] as const;

/** 8 inimigos comuns — progressão de dificuldade / recompensas a cada 90s. */
export const COMMON_ENEMY_TYPE_SEEDS: EnemyTypeSeedRow[] = [
  {
    name: "Zumbi Fraco",
    isBoss: false,
    hpBase: 40,
    speed: 1.8,
    damage: 1.0,
    attackSpeed: 1000,
    color: "#6b8f3a",
    scale: 1,
    unlockTime: 0,
    xpReward: 5,
    goldReward: 1,
    normalDiamondChance: 0.02,
    purpleDiamondChance: 0,
  },
  {
    name: "Rato Corredor",
    isBoss: false,
    hpBase: 25,
    speed: 3.2,
    damage: 0.8,
    attackSpeed: 800,
    color: "#8b7355",
    scale: 0.7,
    unlockTime: 0,
    xpReward: 8,
    goldReward: 1,
    normalDiamondChance: 0.03,
    purpleDiamondChance: 0,
  },
  {
    name: "Esqueleto Guerreiro",
    isBoss: false,
    hpBase: 90,
    speed: 2.0,
    damage: 1.5,
    attackSpeed: 1000,
    color: "#d4d4d8",
    scale: 1.1,
    unlockTime: 90,
    xpReward: 15,
    goldReward: 3,
    normalDiamondChance: 0.05,
    purpleDiamondChance: 0,
  },
  {
    name: "Arqueiro Sombrio (Ranged)",
    isBoss: false,
    hpBase: 60,
    speed: 1.5,
    damage: 1.8,
    attackSpeed: 2000,
    color: "#2dd4bf",
    scale: 0.92,
    unlockTime: 180,
    xpReward: 22,
    goldReward: 5,
    normalDiamondChance: 0.07,
    purpleDiamondChance: 0,
  },
  {
    name: "Brutamontes (Tank)",
    isBoss: false,
    hpBase: 250,
    speed: 1.1,
    damage: 2.5,
    attackSpeed: 1200,
    color: "#7c2d12",
    scale: 1.6,
    unlockTime: 270,
    xpReward: 35,
    goldReward: 8,
    normalDiamondChance: 0.1,
    purpleDiamondChance: 0.002,
  },
  {
    name: "Assassino Fantasma (Dasher)",
    isBoss: false,
    hpBase: 90,
    speed: 4.0,
    damage: 2.0,
    attackSpeed: 700,
    color: "#a855f7",
    scale: 0.8,
    unlockTime: 360,
    xpReward: 50,
    goldReward: 12,
    normalDiamondChance: 0.12,
    purpleDiamondChance: 0.004,
  },
  {
    name: "Cavaleiro Corrompido",
    isBoss: false,
    hpBase: 350,
    speed: 1.6,
    damage: 3.5,
    attackSpeed: 1100,
    color: "#44403c",
    scale: 1.8,
    unlockTime: 450,
    xpReward: 80,
    goldReward: 20,
    normalDiamondChance: 0.15,
    purpleDiamondChance: 0.008,
  },
  {
    name: "Senhor da Guerra (Elite)",
    isBoss: false,
    hpBase: 700,
    speed: 2.2,
    damage: 5.0,
    attackSpeed: 900,
    color: "#b91c1c",
    scale: 2.2,
    unlockTime: 540,
    xpReward: 150,
    goldReward: 35,
    normalDiamondChance: 0.2,
    purpleDiamondChance: 0.015,
  },
];

/** 15 novos inimigos — progressão ao longo das 50 fases / endless. */
export const EXPANSION_ENEMY_TYPE_SEEDS: EnemyTypeSeedRow[] = [
  {
    name: "Cão Raivoso",
    isBoss: false,
    hpBase: 35,
    speed: 4.6,
    damage: 1.2,
    attackSpeed: 650,
    color: "#a16207",
    scale: 0.75,
    unlockTime: 30,
    xpReward: 10,
    goldReward: 2,
    normalDiamondChance: 0.04,
    purpleDiamondChance: 0,
  },
  {
    name: "Lutador de Rua",
    isBoss: false,
    hpBase: 110,
    speed: 2.3,
    damage: 1.8,
    attackSpeed: 950,
    color: "#c2410c",
    scale: 1.15,
    unlockTime: 70,
    xpReward: 18,
    goldReward: 4,
    normalDiamondChance: 0.06,
    purpleDiamondChance: 0,
  },
  {
    name: "Mercenário Ágil (Dasher)",
    isBoss: false,
    hpBase: 95,
    speed: 4.2,
    damage: 2.2,
    attackSpeed: 720,
    color: "#0d9488",
    scale: 0.95,
    unlockTime: 130,
    xpReward: 28,
    goldReward: 6,
    normalDiamondChance: 0.08,
    purpleDiamondChance: 0.001,
  },
  {
    name: "Gladiador Blindado",
    isBoss: false,
    hpBase: 320,
    speed: 1.2,
    damage: 2.8,
    attackSpeed: 1300,
    color: "#57534e",
    scale: 1.7,
    unlockTime: 210,
    xpReward: 40,
    goldReward: 9,
    normalDiamondChance: 0.1,
    purpleDiamondChance: 0.002,
  },
  {
    name: "Xamã Sombrio (Ranged)",
    isBoss: false,
    hpBase: 85,
    speed: 1.4,
    damage: 2.4,
    attackSpeed: 2200,
    color: "#6d28d9",
    scale: 1.0,
    unlockTime: 250,
    xpReward: 32,
    goldReward: 7,
    normalDiamondChance: 0.09,
    purpleDiamondChance: 0.002,
  },
  {
    name: "Berserker Enlouquecido",
    isBoss: false,
    hpBase: 180,
    speed: 2.8,
    damage: 3.2,
    attackSpeed: 800,
    color: "#dc2626",
    scale: 1.25,
    unlockTime: 320,
    xpReward: 45,
    goldReward: 11,
    normalDiamondChance: 0.11,
    purpleDiamondChance: 0.003,
  },
  {
    name: "Assassino de Aluguel (Dasher)",
    isBoss: false,
    hpBase: 100,
    speed: 4.5,
    damage: 3.5,
    attackSpeed: 600,
    color: "#1e1b4b",
    scale: 0.85,
    unlockTime: 400,
    xpReward: 55,
    goldReward: 14,
    normalDiamondChance: 0.13,
    purpleDiamondChance: 0.005,
  },
  {
    name: "Golias de Aço",
    isBoss: false,
    hpBase: 550,
    speed: 0.95,
    damage: 4.0,
    attackSpeed: 1400,
    color: "#71717a",
    scale: 2.1,
    unlockTime: 480,
    xpReward: 70,
    goldReward: 18,
    normalDiamondChance: 0.14,
    purpleDiamondChance: 0.006,
  },
  {
    name: "Monge Corrompido",
    isBoss: false,
    hpBase: 220,
    speed: 2.0,
    damage: 2.6,
    attackSpeed: 1000,
    color: "#86198f",
    scale: 1.2,
    unlockTime: 600,
    xpReward: 65,
    goldReward: 16,
    normalDiamondChance: 0.14,
    purpleDiamondChance: 0.007,
  },
  {
    name: "Necromancer (Ranged)",
    isBoss: false,
    hpBase: 160,
    speed: 1.3,
    damage: 2.9,
    attackSpeed: 2400,
    color: "#365314",
    scale: 1.1,
    unlockTime: 660,
    xpReward: 75,
    goldReward: 20,
    normalDiamondChance: 0.15,
    purpleDiamondChance: 0.008,
  },
  {
    name: "Gigante de Pedra",
    isBoss: false,
    hpBase: 800,
    speed: 0.85,
    damage: 5.5,
    attackSpeed: 1600,
    color: "#78716c",
    scale: 2.4,
    unlockTime: 720,
    xpReward: 100,
    goldReward: 28,
    normalDiamondChance: 0.17,
    purpleDiamondChance: 0.01,
  },
  {
    name: "Espectro Etéreo (Dasher)",
    isBoss: false,
    hpBase: 140,
    speed: 3.8,
    damage: 3.0,
    attackSpeed: 750,
    color: "#67e8f9",
    scale: 0.9,
    unlockTime: 780,
    xpReward: 90,
    goldReward: 24,
    normalDiamondChance: 0.16,
    purpleDiamondChance: 0.009,
  },
  {
    name: "Ciborgue de Combate",
    isBoss: false,
    hpBase: 280,
    speed: 2.6,
    damage: 4.2,
    attackSpeed: 550,
    color: "#0369a1",
    scale: 1.35,
    unlockTime: 840,
    xpReward: 110,
    goldReward: 30,
    normalDiamondChance: 0.18,
    purpleDiamondChance: 0.012,
  },
  {
    name: "Guardião do Templo",
    isBoss: false,
    hpBase: 450,
    speed: 1.7,
    damage: 6.0,
    attackSpeed: 1100,
    color: "#ca8a04",
    scale: 1.9,
    unlockTime: 900,
    xpReward: 130,
    goldReward: 36,
    normalDiamondChance: 0.2,
    purpleDiamondChance: 0.014,
  },
];

/** Bosses escalonados (agenda Endless com intervalo decrescente / chefes de fase). */
export const BOSS_ENEMY_TYPE_SEEDS: EnemyTypeSeedRow[] = [
  {
    name: "Boss 1 (O Titã)",
    isBoss: true,
    hpBase: 520,
    speed: 0.75,
    damage: 2.0,
    attackSpeed: 1600,
    color: "#5b21b6",
    scale: 2.2,
    unlockTime: 0,
    xpReward: 200,
    goldReward: 50,
    normalDiamondChance: 0.5,
    purpleDiamondChance: 0,
  },
  {
    name: "Boss 2 (O Ceifador)",
    isBoss: true,
    hpBase: 3500,
    speed: 1.1,
    damage: 5.0,
    attackSpeed: 1000,
    color: "#a16207",
    scale: 3.0,
    unlockTime: 0,
    xpReward: 500,
    goldReward: 100,
    normalDiamondChance: 1,
    purpleDiamondChance: 0,
  },
  {
    name: "Titã de Magma",
    isBoss: true,
    hpBase: 8000,
    speed: 1.0,
    damage: 7.5,
    attackSpeed: 900,
    color: "#ea580c",
    scale: 3.4,
    unlockTime: 0,
    xpReward: 900,
    goldReward: 180,
    normalDiamondChance: 1,
    purpleDiamondChance: 0.05,
  },
];

export const ENEMY_TYPE_SEEDS: EnemyTypeSeedRow[] = [
  ...COMMON_ENEMY_TYPE_SEEDS,
  ...EXPANSION_ENEMY_TYPE_SEEDS,
  ...BOSS_ENEMY_TYPE_SEEDS,
];
