/** Metadados estáticos dos membros (sem lógica de buff). */
export const TEAM_MEMBERS_META_SEEDS = [
  { id: "bandage_boy", name: "Bandage Boy", tier: "common", role: "cutman", tagline: "Fita rápida entre os rounds." },
  { id: "gym_rat", name: "Gym Rat", tier: "common", role: "sparring", tagline: "Parceiro de saco barato." },
  { id: "water_boy", name: "Water Boy", tier: "common", role: "vitality", tagline: "Hidratação básica." },
  { id: "towel_toss", name: "Towel Toss", tier: "common", role: "cutman", tagline: "Toalha gelada no canto." },
  { id: "roadwork_runner", name: "Roadwork Runner", tier: "common", role: "sparring", tagline: "Quilômetros antes do sol." },
  { id: "stitch_sam", name: "Stitch Sam", tier: "uncommon", role: "cutman", tagline: "Costura cortes no canto." },
  { id: "pad_holder", name: "Pad Holder", tier: "uncommon", role: "sparring", tagline: "Treino de pads constante." },
  { id: "meal_prep", name: "Meal Prep Mia", tier: "uncommon", role: "vitality", tagline: "Cardápio de campeão amador." },
  { id: "ice_bucket", name: "Ice Bucket", tier: "uncommon", role: "cutman", tagline: "Recuperação pós-round." },
  { id: "focus_mitt", name: "Focus Mitt", tier: "uncommon", role: "coach", tagline: "Timing de jab e entrada." },
  { id: "ringside_doc", name: "Ringside Doc", tier: "rare", role: "cutman", tagline: "Médico de plantão no ringue." },
  { id: "sparring_ace", name: "Sparring Ace", tier: "rare", role: "sparring", tagline: "Pressão real no sparring." },
  { id: "strength_coach", name: "Strength Coach", tier: "rare", role: "vitality", tagline: "Força funcional e core." },
  { id: "corner_tactician", name: "Corner Tactician", tier: "rare", role: "coach", tagline: "Lê o adversário no canto." },
  { id: "push_specialist", name: "Push Specialist", tier: "rare", role: "sparring", tagline: "Clinches e empurrões de escola." },
  { id: "skill_scout", name: "Skill Scout", tier: "rare", role: "coach", tagline: "Olheiro de especiais." },
  { id: "prime_cutman", name: "Prime Cutman", tier: "epic", role: "cutman", tagline: "Para sangramento em segundos." },
  { id: "elite_spar", name: "Elite Spar", tier: "epic", role: "sparring", tagline: "Sparring de elite internacional." },
  { id: "head_coach", name: "Head Coach", tier: "epic", role: "coach", tagline: "Estratégia e timing de skills." },
  { id: "money_manager", name: "Money Manager", tier: "epic", role: "manager", tagline: "Contratos e sponsors." },
  { id: "range_finder", name: "Range Finder", tier: "epic", role: "coach", tagline: "Distância perfeita de jab." },
  { id: "purple_agent", name: "Purple Agent", tier: "epic", role: "manager", tagline: "Contratos com o mercado roxo." },
  { id: "iron_doc", name: "Iron Doc", tier: "legendary", role: "cutman", tagline: "Lenda dos cantos sangrentos." },
  { id: "shadow_spar", name: "Shadow Spar", tier: "legendary", role: "sparring", tagline: "Treina como luta — e luta como treina." },
  { id: "titan_prep", name: "Titan Prep", tier: "legendary", role: "vitality", tagline: "Corpo de aço, fôlego infinito." },
  { id: "master_coach", name: "Master Coach", tier: "legendary", role: "coach", tagline: "O cérebro por trás do cinturão." },
  { id: "golden_manager", name: "Golden Manager", tier: "legendary", role: "manager", tagline: "Transforma rounds em fortuna." },
  { id: "echo_striker", name: "Echo Striker", tier: "legendary", role: "sparring", tagline: "Cada golpe ecoa nas skills." },
  { id: "vault_broker", name: "Vault Broker", tier: "legendary", role: "manager", tagline: "Ouro, diamantes e o cofre roxo." },
] as const;
